import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import './styles/app.css';

const roboto = Poppins({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Pato's Home Page",
  description: 'Generated by me',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={` ${roboto.className} antialiased`}>{children}</body>
    </html>
  );
}
